Unit tests
enjin/enjin-java-sdk pull request #21
Opened 2020-08-27 22:45 UTC by BishopJohnson

2020-09-15 23:32 UTC, Favorlock reviewed
You've still got a lot of tests to make. Every class in the SDK should have unit tests.

2020-09-15 23:32 UTC, Favorlock commented on sdk/src/test/java/com/enjin/sdk/PlatformUtils.java
> +    }
Might be easier to define a string constant containing the json representation of the Platform and use GSON to deserialize that. Would eliminate the need for you to create the object via reflection.

2020-10-23 20:40 UTC, Favorlock commented on sdk/src/test/java/com/enjin/sdk/PlatformUtils.java
> +    }
Could simplify this (and methods it depends on) by storing a fake response as a constant and using GSON to deserialize it to the type (emulates Retrofit).

2020-10-23 21:26 UTC, Favorlock requested changes

2020-10-23 21:26 UTC, Favorlock commented on sdk/src/test/java/com/enjin/sdk/models/FilterTest.java
> +        filters.add(new TestableFilter());
Don't think this makes sense as there isn't any reason to test the same input multiple times.

2020-10-24 01:02 UTC, BishopJohnson commented on sdk/src/test/java/com/enjin/sdk/models/FilterTest.java
> +        filters.add(new TestableFilter());
That section is to setup a list of other filters, so that when testing methods such as `Filter.and(T... others)` we can see if those filters did get stored.

2020-10-24 15:47 UTC, Favorlock approved these changes

2020-10-26 16:18 UTC, merged