Updated v2 SDK for new platform APIs
enjin/enjin-java-sdk pull request #23
Opened 2020-10-06 18:38 UTC by BishopJohnson

2020-10-12 22:32 UTC, Favorlock requested changes

2020-10-12 22:32 UTC, Favorlock commented on sdk/src/main/java/com/enjin/sdk/schemas/project/mutations/UnlinkWallet.java
> +        return set("address", ethAddress);
This shouldn't have been changed. The variable is defined in the template as the following:

#arg ethAddress String!

2020-10-12 22:41 UTC, BishopJohnson commented on sdk/src/main/java/com/enjin/sdk/schemas/project/mutations/UnlinkWallet.java
> +        return set("address", ethAddress);
I checked the App Schema that currently exists on the v2 platform that Brad updated. On that, the field name for the `UnlinkWallet` mutation was indeed changed from `ethAddress` to `address`. I also updated this in the GraphQL templates repository.

2020-10-18 18:12 UTC, Favorlock approved these changes

2020-10-19 15:31 UTC, merged